insert into Events (id, name, startingDate, endingDate, location, description, image) values (1, 'Buzzdog', '2/3/2021', '1/2/2022', '9 Sheridan Court', 'Disc degeneration NOS', '');
insert into Events (id, name, startingDate, endingDate, location, description, image) values (2, 'Wikibox', '3/1/2021', '4/11/2022', '669 Moulton Junction', 'Tox eff nonmed subst NEC', '');
insert into Events (id, name, startingDate, endingDate, location, description, image) values (3, 'Abatz', '9/13/2020', '9/30/2021', '72710 Graedel Place', 'Semicircul canal fistula', '');
insert into Events (id, name, startingDate, endingDate, location, description, image) values (4, 'Edgeblab', '4/25/2021', '9/20/2021', '506 Beilfuss Hill', 'Ac osteomyelitis NEC', '');
insert into Events (id, name, startingDate, endingDate, location, description, image) values (5, 'Gevee', '11/10/2020', '9/28/2021', '586 Delladonna Terrace', 'Conjunctival diphtheria', '');
insert into Events (id, name, startingDate, endingDate, location, description, image) values (6, 'Bubblemix', '1/26/2021', '5/24/2022', '62 Lindbergh Junction', 'Prob-head/neck/trunk NOS', '');
insert into Events (id, name, startingDate, endingDate, location, description, image) values (7, 'Tambee', '3/14/2021', '6/24/2021', '0891 Maple Wood Pass', 'Postabortion compl NOS', '');
insert into Events (id, name, startingDate, endingDate, location, description, image) values (8, 'Lajo', '5/2/2021', '6/3/2021', '5706 Longview Place', 'Inj NEC caused by animal', '');
insert into Events (id, name, startingDate, endingDate, location, description, image) values (9, 'Babblestorm', '4/3/2021', '1/6/2022', '0 Mayer Avenue', 'Ulcer esophagus w bleed', '');
insert into Events (id, name, startingDate, endingDate, location, description, image) values (10, 'Zoovu', '5/21/2021', '5/17/2022', '0502 Buena Vista Street', 'Hodgkins granulom inguin', '');
insert into Events (id, name, startingDate, endingDate, location, description, image) values (11, 'Einti', '12/31/2020', '7/26/2021', '045 Marquette Pass', 'Anxiety state NOS', '');
insert into Events (id, name, startingDate, endingDate, location, description, image) values (12, 'Edgetag', '2/7/2021', '11/30/2021', '137 Burning Wood Circle', 'Hemarthrosis-mult jts', '');
insert into Events (id, name, startingDate, endingDate, location, description, image) values (13, 'Flipbug', '4/26/2021', '6/19/2021', '173 Bellgrove Alley', 'Schizophr dis resid-chr', '');
insert into Events (id, name, startingDate, endingDate, location, description, image) values (14, 'Bubblemix', '1/23/2021', '2/22/2022', '27321 Monument Place', 'Pelv fx-clos/pelv disrup', '');
insert into Events (id, name, startingDate, endingDate, location, description, image) values (15, 'Kamba', '11/18/2020', '10/24/2021', '21204 Kim Street', 'Mild/NOS preeclamp-antep', '');
