insert into Exhibitors (id, eMail, name, company, description) values (1, 'gibbeson0@tinyurl.com', 'Geneva', 'Cogidoo', 'Removal spine stim lead');
insert into Exhibitors (id, eMail, name, company, description) values (2, 'ajacquot1@chicagotribune.com', 'Anson', 'Centimia', 'Remove corneal implant');
insert into Exhibitors (id, eMail, name, company, description) values (3, 'pertelt2@usda.gov', 'Patsy', 'Ozu', 'Type 2 tympanoplasty');
insert into Exhibitors (id, eMail, name, company, description) values (4, 'lmuzzullo3@zdnet.com', 'Lincoln', 'Dynabox', 'Lap hern ant abd-gft NEC');
insert into Exhibitors (id, eMail, name, company, description) values (5, 'jbenedick4@timesonline.co.uk', 'Jeremy', 'Roomm', 'Thumb reconstruction NEC');
insert into Exhibitors (id, eMail, name, company, description) values (6, 'hisabell5@devhub.com', 'Harriet', 'Chatterbridge', 'Thyroid reimplantation');
insert into Exhibitors (id, eMail, name, company, description) values (7, 'jvater6@scribd.com', 'Josepha', 'Topicblab', 'Tarsal tunnel release');
insert into Exhibitors (id, eMail, name, company, description) values (8, 'kmcilwain7@businesswire.com', 'Kerk', 'LiveZ', 'Urethral reanastomosis');
insert into Exhibitors (id, eMail, name, company, description) values (9, 'ncarlens8@hc360.com', 'Nessi', 'Bluezoom', 'Substern thyroidect NOS');
insert into Exhibitors (id, eMail, name, company, description) values (10, 'ebonavia9@a8.net', 'Esmeralda', 'Skalith', 'Skull transilluminat');
insert into Exhibitors (id, eMail, name, company, description) values (11, 'crowberrya@europa.eu', 'Camile', 'Oyoba', 'Parasitology-blood');
insert into Exhibitors (id, eMail, name, company, description) values (12, 'obilbrookb@blogs.com', 'Oren', 'Yozio', 'Interphalangeal fusion');
insert into Exhibitors (id, eMail, name, company, description) values (13, 'fheustacec@kickstarter.com', 'Forrester', 'Tazzy', 'Mouth incision NOS');
insert into Exhibitors (id, eMail, name, company, description) values (14, 'sbanfilld@dot.gov', 'Shelley', 'Quinu', 'Control anal hemorrhage');
insert into Exhibitors (id, eMail, name, company, description) values (15, 'bsprigine@cnet.com', 'Bebe', 'Tagopia', 'Pedicle attach to mouth');
