insert into Stands (id, U_Number, size, description) values (1, 1, 19, 'Trabecul carneae cord op');
insert into Stands (id, U_Number, size, description) values (2, 2, 17, 'Tube & uterus x-ray NEC');
insert into Stands (id, U_Number, size, description) values (3, 3, 10, 'Fat graft to breast');
insert into Stands (id, U_Number, size, description) values (4, 4, 19, 'Nasophary contrast x-ray');
insert into Stands (id, U_Number, size, description) values (5, 5, 19, 'Fit arm prosthesis NOS');
insert into Stands (id, U_Number, size, description) values (6, 6, 27, 'Trabecul carneae cord op');
insert into Stands (id, U_Number, size, description) values (7, 7, 28, 'Endosc retro cholangio');
insert into Stands (id, U_Number, size, description) values (8, 8, 19, 'Hemorrhoid cauterizat');
insert into Stands (id, U_Number, size, description) values (9, 9, 15, 'Other thyroid operations');
insert into Stands (id, U_Number, size, description) values (10, 10, 11, 'Loc exc bony palate les');
insert into Stands (id, U_Number, size, description) values (11, 11, 25, 'Manual rupt joint adhes');
insert into Stands (id, U_Number, size, description) values (12, 12, 14, 'Allo hem stem ct w/o pur');
insert into Stands (id, U_Number, size, description) values (13, 13, 30, 'Ins noninfl penis prosth');
insert into Stands (id, U_Number, size, description) values (14, 14, 24, 'Insert sengstaken tube');
insert into Stands (id, U_Number, size, description) values (15, 15, 13, 'Knee structure division');
insert into Stands (id, U_Number, size, description) values (16, 16, 20, 'Ptosis rep-levat mus adv');
insert into Stands (id, U_Number, size, description) values (17, 17, 12, 'Exc lacrimal gland NOS');
insert into Stands (id, U_Number, size, description) values (18, 18, 20, 'Lap ing hern-graft NOS');
insert into Stands (id, U_Number, size, description) values (19, 19, 24, 'Oth tib/fib repair/plast');
insert into Stands (id, U_Number, size, description) values (20, 20, 28, 'Rev interspine device');
insert into Stands (id, U_Number, size, description) values (21, 21, 11, 'Femoral biopsy');
insert into Stands (id, U_Number, size, description) values (22, 22, 22, 'Perc robotic assist proc');
insert into Stands (id, U_Number, size, description) values (23, 23, 18, 'Adrenal lesion excision');
insert into Stands (id, U_Number, size, description) values (24, 24, 20, 'Imp cardiomyostimul sys');
insert into Stands (id, U_Number, size, description) values (25, 25, 25, 'Other isotope function');
insert into Stands (id, U_Number, size, description) values (26, 26, 26, 'Rep anuls fibros NEC/NOS');
insert into Stands (id, U_Number, size, description) values (27, 27, 29, 'Pancreatic tube irrigat');
insert into Stands (id, U_Number, size, description) values (28, 28, 16, 'Control bladd hemorrhage');
insert into Stands (id, U_Number, size, description) values (29, 29, 16, 'Multiple sinus incision');
insert into Stands (id, U_Number, size, description) values (30, 30, 10, 'Ovarian cyst marsupializ');
